export const matchCardStyles = {
  card: 'flex flex-col rounded-card border bg-pan',
  cardLive: 'border-bd2',
  cardIdle: 'border-bd',
  header: 'flex items-center gap-2 border-b border-bd px-[13px] py-[9px]',
  liveDot: 'size-[7px] flex-none animate-live-dot rounded-full bg-ac',
  status: 'text-[9px] font-bold tracking-[-.01em] whitespace-nowrap',
  statusTone: {
    agendado: 'text-am',
    ao_vivo: 'text-ac',
    encerrado: 'text-tx4',
    adiado: 'text-am',
    cancelado: 'text-vm',
    wo: 'text-tx4',
  },
  schedule: 'ml-auto text-[11px] whitespace-nowrap text-tx4',
  scoreboard: 'grid grid-cols-[1fr_auto_1fr] items-center gap-3 px-[14px] py-5',
  teamColumn: 'flex min-w-0 flex-col items-center gap-2',
  teamName: 'text-center text-[12.2px] font-bold tracking-[-.01em] text-balance',
  scoreColumn: 'flex flex-col items-center gap-[5px]',
  scoreLine: 'flex items-baseline gap-[11px]',
  score: 'text-[41.4px] leading-[.85] font-bold nums',
  scoreEmpty: 'text-bd3',
  scoreLoser: 'text-tx2',
  scoreWinner: 'text-tx',
  scoreSeparator: 'text-[21.6px] font-semibold text-bd2',
  clock: 'text-[11.5px] font-semibold tracking-[.06em]',
  clockLive: 'text-ac',
  clockIdle: 'text-tx4',
  footer: 'flex items-center gap-[10px] border-t border-bd px-[13px] py-[10px]',
  venue: 'min-w-0 truncate text-[10.5px] whitespace-nowrap text-tx3',
  action: 'ml-auto flex h-[30px] flex-none items-center px-[13px] text-[10.3px] font-bold tracking-[-.01em]',
  actionPrimary: 'bg-ac text-bg',
  actionSecondary: 'border border-bd2 bg-transparent text-tx hover:border-tx',
} as const
