export const championshipListSkeletonStyles = {
  root: 'min-h-0 flex-1 overflow-hidden p-5',
  columns: 'mx-auto grid max-w-[1240px] grid-cols-[repeat(auto-fit,minmax(min(100%,400px),1fr))] gap-[18px]',
  column: 'flex min-w-0 flex-col gap-3',
  columnHeader: 'flex items-center gap-[10px] border-b-2 border-bd pb-[9px]',
  columnTag: 'h-[26px] w-[84px]',
  columnSummary: 'h-[11px] w-[200px] max-w-[60%]',
  card: 'flex flex-col gap-3 rounded-card border border-t-2 border-bd bg-pan p-4',
  cardHeader: 'flex items-start gap-[10px]',
  cardTitleBlock: 'flex flex-1 flex-col gap-[5px]',
  cardName: 'h-[22px] w-[74%]',
  cardStatus: 'h-[10px] w-[52%]',
  cardTag: 'h-5 w-[62px]',
  podium: 'flex flex-col gap-[9px] bg-pan2 px-[10px] py-2',
  podiumLine: 'h-3',
  matchStatus: 'h-[35px] rounded-card border border-bd bg-pan2',
  openButton: 'h-9 bg-pan2',
} as const
