export const championshipCardStyles = {
  card: 'flex animate-rise-in flex-col gap-3 rounded-card border bg-pan p-4 text-tx transition-[background,border-color] duration-200 hover:border-bd2 hover:bg-pan4',
  cardLive: 'border-bd2',
  cardIdle: 'border-bd',
  header: 'flex items-start gap-[10px]',
  titleBlock: 'flex min-w-0 flex-col gap-[5px]',
  name: 'text-[19.8px] leading-none font-bold tracking-[-.01em] text-pretty',
  statusLine: 'text-[10.5px] tracking-[.08em] text-tx4',
  categoryTag: 'self-start',
  podium: 'flex flex-col gap-px bg-pan2 px-[10px] py-2',
  podiumRow: 'flex min-w-0 items-center gap-[9px] py-1',
  podiumPosition: 'w-3 flex-none text-[11px]',
  podiumPositionLeader: 'text-ac',
  podiumPositionOther: 'text-tx4',
  podiumTeam: 'min-w-0 truncate text-[11.7px] font-bold tracking-[-.01em]',
  podiumTeamLeader: 'text-tx',
  podiumTeamOther: 'text-tx2',
  podiumPoints: 'ml-auto flex-none text-[12.5px] nums',
  podiumPointsLeader: 'font-semibold text-tx',
  podiumPointsOther: 'text-tx2',
  emptyPodiumRow: 'flex items-center gap-[9px] py-1',
  emptyPodiumPosition: 'w-3 flex-none text-[9.9px] text-tx4',
  emptyPodiumCrest: 'h-[19px] w-4 flex-none',
  emptyPodiumMessage: 'text-[10.8px] font-semibold tracking-[-.01em] text-tx4',
  status: 'flex min-w-0 items-center gap-2 rounded-card border px-[10px] py-2',
  statusLive: 'border-ac bg-pan2',
  statusIdle: 'border-bd bg-transparent',
  liveDot: 'size-[7px] flex-none animate-live-dot rounded-full bg-ac',
  scheduleIcon: 'text-tx4',
  statusText: 'min-w-0 truncate text-[11.3px] font-bold tracking-[-.01em]',
  statusTextLive: 'text-tx',
  statusTextIdle: 'text-tx2',
  statusMeta: 'ml-auto flex-none text-[11px]',
  statusMetaLive: 'text-ac',
  statusMetaIdle: 'text-tx4',
  openLabel: 'flex h-9 items-center justify-center rounded-card border border-bd2 text-[11.3px] font-bold tracking-[-.01em] transition-colors',
  openLabelLive: 'text-ac',
  openLabelIdle: 'text-tx2',
} as const
