export const reviewStepStyles = {
  step: 'flex min-h-0 max-w-[1000px] flex-1 animate-fade-up flex-col gap-[14px]',
  hero: 'flex flex-none flex-wrap items-center gap-5 bg-pan2 px-5 py-4 chamfer mobile:px-4',
  heroText: 'min-w-0',
  championshipLine: 'mb-2 flex flex-wrap items-center gap-3',
  championshipName: 'text-[10.8px] font-semibold tracking-[-.01em] text-tx2',
  title: 'text-[18.9px] leading-[1.15] font-bold tracking-[-.01em] text-pretty whitespace-pre-wrap',
  subtitle: 'mt-[6px] text-[11.3px] font-semibold tracking-[-.01em] text-tx2',
  readyBadge: 'ml-auto -skew-x-12 rounded-card border border-ac px-4 py-2',
  readyBadgeText: 'block skew-x-12 text-[11.3px] font-bold tracking-[-.01em] text-ac',
  lineups: 'grid flex-none grid-cols-[repeat(auto-fit,minmax(min(100%,320px),1fr))] gap-[14px]',
  lineup: 'flex min-h-0 flex-col gap-[10px] bg-pan2 px-4 py-[14px] chamfer',
  lineupHeader: 'flex flex-none flex-wrap items-center gap-[10px]',
  teamName: 'text-[13.5px] font-bold tracking-[-.01em]',
  starters: 'grid grid-cols-[repeat(auto-fit,minmax(130px,1fr))] content-start gap-x-[14px] gap-y-[5px]',
  starter: 'flex min-w-0 items-baseline gap-2 text-[13px]',
  starterShirtNumber: 'w-[22px] flex-none font-bold nums',
  starterName: 'truncate whitespace-nowrap',
  broadcast: 'flex flex-none flex-wrap items-center gap-[22px] bg-pan px-4 py-3',
  broadcastTitle: 'text-[10.3px] font-semibold tracking-[-.01em] text-tx4',
  fact: 'flex items-baseline gap-[10px]',
  factLabel: 'text-[9.9px] font-semibold tracking-[-.01em] text-tx4',
  factValue: 'text-[12.2px] font-bold tracking-[-.01em]',
} as const
