export const lineupCardStyles = {
  card: 'flex min-h-0 min-w-0 flex-col bg-pan2 chamfer',
  header: 'flex flex-wrap items-center gap-[10px] border-b border-bd px-[18px] py-4 mobile:px-[14px]',
  teamName: 'text-[14.4px] font-bold tracking-[-.01em]',
  starterCount: 'flex-none rounded-card border px-[10px] py-1 text-[10.3px] font-bold tracking-[-.01em]',
  starterCountComplete: 'border-ac text-ac',
  starterCountIncomplete: 'border-am text-am',
  sourceLine: 'border-b border-bd px-[18px] py-2 text-[11.5px] text-tx4 mobile:px-[14px]',
  playerList: 'min-h-[140px] flex-1 overflow-x-hidden overflow-y-auto mobile:flex-none mobile:overflow-visible',
  emptyMessage: 'px-[18px] py-4 text-[12.5px] text-tx4',
  player: 'flex h-[42px] w-full items-center gap-3 border-t border-bd px-[18px] text-left text-tx mobile:px-[14px]',
  playerStarter: 'bg-pan',
  playerReserve: 'bg-transparent',
  playerLocked: 'cursor-not-allowed',
  playerAvailable: 'cursor-pointer',
  checkbox: 'size-4 flex-none appearance-none rounded-card border',
  checkboxUnchecked: 'border-bd2 bg-transparent',
  shirtNumber: 'w-6 flex-none text-[13.5px] font-bold nums',
  shirtNumberReserve: 'text-tx4',
  playerName: 'min-w-0 flex-1 truncate text-[14px] whitespace-nowrap',
  position: 'text-[9.9px] font-semibold tracking-[-.01em] text-tx4 uppercase',
} as const
