export const championshipDetailSkeletonStyles = {
  root: 'flex min-h-0 flex-1 flex-col',
  tabs: 'flex gap-1 border-b border-bd bg-pan px-5 pt-[14px] pb-3',
  standingsTab: 'h-[30px] w-[150px]',
  statisticsTab: 'h-[30px] w-[90px]',
  matchesTab: 'h-[30px] w-[70px]',
  body: 'flex flex-wrap items-start gap-[18px] overflow-hidden p-5',
  standingsColumn: 'flex min-w-0 flex-[1_1_560px] flex-col gap-[10px]',
  standingsTitle: 'h-4 w-[260px]',
  table: 'overflow-hidden rounded-card border border-bd bg-pan',
  tableHeader: 'h-[34px] rounded-none bg-pan2',
  row: 'flex h-11 items-center gap-3 border-b border-pan2 px-[14px]',
  rowPosition: 'h-3 w-4',
  rowCrest: 'h-[13px] w-[11px]',
  rowName: 'h-3 w-[40%]',
  rowPoints: 'ml-auto h-4 w-6',
  roundColumn: 'flex min-w-[280px] flex-[0_1_340px] flex-col gap-[10px]',
  roundTitle: 'h-4 w-[120px]',
  roundCard: 'h-[88px] bg-pan2',
} as const
