export const newMatchWizardSkeletonStyles = {
  wizard: 'flex min-h-[420px] flex-1 flex-col bg-bg',
  stepper: 'flex flex-none overflow-hidden border-b border-bd bg-pan',
  step: 'flex min-w-[158px] flex-[1_1_0] items-center gap-[11px] border-b-2 border-bd px-4 py-[13px] [&+&]:border-l [&+&]:border-l-bd',
  stepBadge: 'size-6 rounded-card',
  stepText: 'flex flex-col gap-[6px]',
  stepTitle: 'h-[10px] w-20',
  stepValue: 'h-2 w-24',
  content: 'flex-1 px-5 py-4 mobile:px-3',
  fields: 'grid max-w-[820px] grid-cols-[repeat(auto-fit,minmax(min(100%,180px),1fr))] gap-4 bg-pan2 p-5 chamfer',
  field: 'flex flex-col gap-[6px]',
  fieldWide: 'col-span-full flex flex-col gap-[6px]',
  fieldLabel: 'h-[10px] w-14',
  fieldInput: 'h-[42px] w-full rounded-card',
  footer: 'flex flex-none items-center gap-[14px] border-t border-bd bg-pan px-5 py-3',
  footerSummary: 'h-[34px] w-[96px] rounded-card',
  footerHint: 'h-[10px] w-56',
  footerBack: 'ml-auto h-11 w-[104px] rounded-card',
  footerNext: 'h-12 w-[128px]',
} as const
