export const newChampionshipPanelStyles = {
  form: 'flex animate-rise-in flex-col gap-4 bg-pan2 p-5 chamfer mobile:p-[14px]',
  title: 'text-[13.5px] font-bold tracking-[-.01em]',
  fields: 'grid grid-cols-[repeat(auto-fit,minmax(min(100%,220px),1fr))] gap-[14px]',
  label: 'mb-[6px] block text-[10.3px] font-semibold tracking-[-.01em] text-tx4',
  input: 'h-10 w-full rounded-card border border-bd2 bg-bg px-3 text-[13px] text-tx outline-none placeholder:text-tx5 focus-visible:border-tx3',
  requiredLabel: 'mb-[6px] block text-[10.3px] font-semibold tracking-[-.01em] text-am',
  categoryOptions: 'flex gap-2',
  categoryOption: 'h-10 flex-1 rounded-card border text-[11.7px] font-bold tracking-[-.01em] transition-colors duration-[140ms]',
  categoryOptionSelected: 'text-bg',
  categoryOptionIdle: 'border-bd2 bg-transparent text-tx2 hover:border-bd3',
  yearInput: 'nums',
  clubsLabel: 'flex items-baseline justify-between gap-3',
  selectedCount: 'nums',
  clubsHint: 'mt-2 text-[11.5px] leading-[1.45] text-tx4',
  failure: 'text-[12px] text-vm',
  actions: 'flex flex-wrap items-center gap-[14px]',
  submitButton: 'h-11 px-5 text-[12.6px] font-bold tracking-[-.01em]',
  submitButtonReady: 'cursor-pointer bg-ac text-bg',
  submitButtonIncomplete: 'cursor-not-allowed bg-bd2 text-tx4',
  submitButtonPending: 'opacity-70',
  cancelButton: 'h-11 rounded-card border border-bd2 bg-transparent px-[18px] text-[11.7px] font-bold tracking-[-.01em] text-tx2 hover:text-tx',
  categoryNotice: 'text-[13px] text-pretty text-tx4',
} as const
