export const wizardStepperStyles = {
  stepper: 'no-scrollbar flex flex-none items-stretch overflow-x-auto border-b border-bd bg-pan',
  step: 'flex min-w-[158px] flex-[1_1_0] items-center gap-[11px] border-b-2 px-4 py-[13px] text-left transition-[background,border-color] duration-[180ms] disabled:cursor-default',
  stepFollowing: 'border-l border-l-bd',
  stepActive: 'bg-pan2',
  stepInactive: 'bg-transparent',
  stepReached: 'border-b-ac',
  stepPending: 'border-b-bd',
  badge: 'flex size-6 flex-none items-center justify-center rounded-card border text-[12px] font-semibold',
  badgeReached: 'border-ac bg-ac text-bg',
  badgePending: 'border-bd2 text-tx4',
  text: 'flex min-w-0 flex-col gap-[2px]',
  title: 'text-[11.7px] font-bold tracking-[-.01em] whitespace-nowrap',
  titleReached: 'text-tx',
  titlePending: 'text-tx3',
  value: 'truncate text-[10px] tracking-[.06em] whitespace-nowrap',
  valueDone: 'text-ac',
  valueActive: 'text-tx2',
  valuePending: 'text-tx5',
} as const
