import { STANDINGS_GRID_CLASS } from '../standings-table/standings-grid'

export const standingsRowStyles = {
  row: 'group animate-rise-in',
  grid: STANDINGS_GRID_CLASS,
  summary: 'h-11 cursor-pointer list-none items-center border-b border-pan2 transition-colors duration-150 group-open:bg-pan2 hover:bg-pan2 compact:h-[46px] [&::-webkit-details-marker]:hidden',
  position: 'font-mono text-[12px] nums',
  positionTop: 'text-ac',
  positionBottom: 'text-vm',
  positionMiddle: 'text-tx2',
  club: 'flex min-w-0 items-center gap-[9px]',
  chevron: 'w-[9px] flex-none text-[13.5px] leading-none text-bd3 transition-transform duration-100 group-open:rotate-90 group-open:text-ac',
  clubName: 'min-w-[54px] flex-[1_1_auto] truncate text-[12.6px] font-bold tracking-[-.01em]',
  points: 'text-center text-[16px] font-extrabold text-tx nums compact:text-[15px]',
  numberCell: 'text-center font-mono text-[12px] nums text-tx2',
  wideOnly: 'compact:hidden',
  goalDifference: 'text-center font-mono text-[12px] nums',
  goalDifferencePositive: 'text-ac',
  goalDifferenceNegative: 'text-vm',
  goalDifferenceEven: 'text-tx4',
  squadPanel: 'flex animate-fade-up flex-col gap-[10px] border-b border-bd bg-pan2 pt-[14px] pr-4 pb-[18px] pl-[46px] mobile:pl-4',
  squadHeader: 'flex flex-wrap items-center gap-[10px]',
  squadTitle: 'text-[11.3px] font-bold tracking-[-.01em] text-tx2',
  squadCount: 'text-[11px] text-tx4',
  squadGrid: 'grid grid-cols-[repeat(auto-fit,minmax(min(100%,200px),1fr))] gap-x-[18px] gap-y-[6px]',
  player: 'flex min-w-0 items-baseline gap-[9px]',
  shirtNumber: 'w-[22px] flex-none text-[12.6px] font-bold nums',
  playerName: 'truncate text-[13.5px] whitespace-nowrap',
  playerPosition: 'ml-auto text-[9.5px] font-semibold tracking-[-.01em] whitespace-nowrap text-tx4 uppercase',
} as const
