export const teamListSkeletonStyles = {
  list: 'max-w-[250px] min-w-[190px] flex-[1_1_210px] bg-pan py-[14px]',
  filterLabelRow: 'px-4 pb-2',
  filterLabel: 'h-[11px] w-[118px]',
  filters: 'flex flex-wrap gap-[6px] px-4 pb-3',
  activeFilter: 'h-[30px] w-[58px]',
  filter: 'h-[30px] w-[54px] bg-pan2',
  teamsLabelRow: 'border-t border-bd px-4 pt-3 pb-2',
  teamsLabel: 'h-[11px] w-[46px]',
  row: 'flex items-center gap-[10px] border-l-[3px] px-4 py-[10px]',
  rowActive: 'border-bd2 bg-pan2',
  rowIdle: 'border-transparent',
  crest: 'h-6 w-5 flex-none hexagon',
  details: 'flex min-w-0 flex-1 flex-col gap-[5px]',
  name: 'h-3',
  category: 'h-[14px] w-[46px]',
  fillFaded: 'bg-pan2',
  fillFilled: 'bg-bd',
} as const
