import { ROSTER_GRID_CLASS } from '../roster-grid/roster-grid'

export const squadWorkspaceSkeletonStyles = {
  grid: ROSTER_GRID_CLASS,
  roster: '@container flex min-h-[300px] min-w-0 flex-[4_1_300px] flex-col bg-pan2',
  header: 'flex flex-wrap items-center gap-3 border-b border-bd px-4 py-3',
  headerCrest: 'h-[27px] w-[22px] flex-none hexagon',
  headerTitles: 'flex min-w-0 flex-col gap-[6px]',
  headerTitle: 'h-[17px] w-[150px]',
  headerSubtitle: 'h-[11px] w-[190px] max-w-full',
  headerSearch: 'h-[38px] min-w-[120px] flex-1 bg-pan',
  headerButton: 'h-[38px] w-[140px] max-w-full flex-[0_1_auto] bg-pan',
  columnHeader: 'border-b border-bd py-2',
  columnHeaderCell: 'h-[10px]',
  columnHeaderNameCell: 'w-[52px]',
  rows: 'min-h-0 flex-1 overflow-hidden',
  row: 'h-11 items-center border-b border-bd',
  numberCell: 'h-[15px]',
  nameCell: 'h-[13px]',
  statCell: 'h-[11px]',
  lastCell: 'w-4',
  cellFaded: 'bg-pan2',
  cellFilled: 'bg-bd',
  sheet: 'flex min-h-[260px] max-w-[420px] min-w-0 flex-[2_1_280px] flex-col gap-[14px] bg-pan px-5 py-[18px] mobile:hidden',
  sheetHeader: 'flex items-center gap-3',
  sheetCrest: 'h-6 w-5 flex-none hexagon',
  sheetTitle: 'h-[15px] w-[148px]',
  sheetCategory: 'h-5 w-[58px]',
  identityFields: 'grid grid-cols-[90px_minmax(0,1fr)] gap-3',
  field: 'flex flex-col gap-[6px]',
  numberLabel: 'h-[10px] w-[56px]',
  nameLabel: 'h-[10px] w-[44px]',
  input: 'h-10 bg-pan2',
  displayNameLabel: 'h-[10px] w-[176px] max-w-full',
  chips: 'flex flex-wrap gap-2',
  positionChip: 'h-[26px] w-[88px] bg-pan2',
  footChip: 'h-[26px] w-[74px] bg-pan2',
  teamChip: 'h-[26px] w-[132px] bg-pan2',
  curiosities: 'flex flex-col gap-[9px]',
  curiositiesLabel: 'h-[10px] w-[92px]',
  firstCuriosity: 'h-[13px] w-[84%]',
  secondCuriosity: 'h-[13px] w-[72%]',
} as const
