export const auditLogSkeletonStyles = {
  container: 'flex flex-col gap-[22px]',
  filters: 'grid grid-cols-[repeat(auto-fit,minmax(min(100%,180px),1fr))] gap-[10px] rounded-card border border-bd bg-pan p-[14px]',
  filter: 'flex flex-col gap-[5px]',
  filterLabelPlaceholder: 'h-[10px] w-[56px]',
  filterFieldPlaceholder: 'h-[34px] rounded-card',
  table: 'flex flex-col overflow-hidden rounded-card border border-bd bg-pan',
  row: 'flex h-[46px] items-center gap-3 px-3',
  rowOdd: 'bg-pan0',
  rowEven: 'bg-pan',
  timePlaceholder: 'h-[10px] w-[100px] flex-none',
  userPlaceholder: 'h-3 w-[110px] flex-none',
  actionPlaceholder: 'h-3 w-[150px] flex-none mobile:hidden',
  entityPlaceholder: 'h-3 w-[30%] mobile:hidden',
} as const
