export const auditTableStyles = {
  emptyState: 'flex min-h-11 items-center justify-center rounded-card border border-dashed border-bd2 px-4 py-3 text-center text-[10.8px] font-bold tracking-[-.01em] text-tx4',
  table: 'flex flex-col overflow-hidden rounded-card border border-bd bg-pan',
  headerRow: 'flex items-center gap-3 border-b border-bd2 px-3 pt-[9px] pb-2 text-[10px] tracking-[.05em] text-tx4 mobile:hidden',
  fixedHeader: 'flex-none',
  timeHeader: 'w-[118px]',
  userHeader: 'w-[140px]',
  actionHeader: 'w-[190px]',
  entityHeader: 'min-w-0 flex-1',
  detailsHeader: 'min-w-0 flex-1 compact:hidden',
  row: 'flex animate-fade-up items-center gap-3 px-3 py-[10px] mobile:flex-wrap mobile:gap-x-3 mobile:gap-y-1',
  rowOdd: 'bg-pan0',
  rowEven: 'bg-pan',
  timeCell: 'w-[118px] flex-none text-[11px] tracking-[.04em] text-tx3 nums mobile:w-auto',
  userCell: 'w-[140px] flex-none truncate text-[12.6px] font-bold tracking-[-.01em] text-tx mobile:w-auto',
  actionCell: 'w-[190px] flex-none truncate text-[12px] text-tx1 mobile:w-full',
  entityCell: 'flex min-w-0 flex-1 flex-col gap-[2px] mobile:w-full mobile:flex-none',
  entityLabel: 'text-[9.5px] tracking-[.06em] text-tx5',
  entityDescription: 'truncate text-[11.7px] font-bold tracking-[-.01em] text-tx2',
  detailsCell: 'min-w-0 flex-1 truncate text-[10.5px] tracking-[.03em] text-tx4 compact:hidden',
} as const
