export const playerSheetSkeletonStyles = {
  closeButton: 'hidden h-[34px] w-[74px] self-end rounded-card mobile:block',
  crest: 'h-6 w-5 flex-none hexagon',
  textBar: 'inline-block h-[0.8em] max-w-full align-middle',
  titleWidth: 'w-[124px]',
  categoryTag: 'h-[28.75px] w-[70px] flex-none rounded-card bg-pan2',
  numberLabelWidth: 'w-[44px]',
  nameLabelWidth: 'w-[34px]',
  readOnlyInput: 'h-10 rounded-card bg-pan2',
  displayNameLabelWidth: 'w-[150px]',
  displayNameWidth: 'w-[72px]',
  chips: ['w-[64px]', 'w-[78px]', 'w-[150px]'],
  chip: 'h-[26.2px] -skew-x-12 rounded-card bg-pan2',
  curiosityMarker: 'bg-bd',
  curiositiesHeadingWidth: 'w-[72px]',
  curiosityWidths: ['w-[92%]', 'w-[68%]'],
  signInWidth: 'w-[160px]',
  noteWidths: ['w-full', 'w-[56%]'],
} as const
