export const topScorersTableStyles = {
  section: 'max-w-[1000px] animate-fade-up',
  header: 'mb-3 flex flex-wrap items-center gap-3',
  title: 'text-[13.5px] font-bold tracking-[-.01em]',
  hint: 'text-[12.5px] text-tx4',
  table: 'overflow-hidden rounded-card border border-bd bg-pan',
  grid: 'grid grid-cols-[34px_minmax(0,1.3fr)_minmax(0,1fr)_52px_52px] gap-x-2 px-4 compact:grid-cols-[26px_minmax(0,1fr)_38px_38px] compact:gap-x-[6px] compact:px-[11px]',
  headerRow: 'border-b border-bd py-[10px] compact:py-[9px]',
  headerCell: 'text-[10.5px] font-semibold tracking-[.14em] whitespace-nowrap text-tx4 compact:text-[9px]',
  headerAlignStart: 'text-left',
  headerAlignStartWideOnly: 'text-left compact:hidden',
  headerAlignCenter: 'text-center',
  row: 'animate-rise-in items-center border-b border-bd py-[11px] compact:py-[10px]',
  rank: 'font-mono text-[12px] nums',
  rankLeader: 'text-ac',
  rankOther: 'text-tx4',
  athlete: 'flex min-w-0 items-baseline gap-[9px]',
  shirtNumber: 'min-w-[18px] text-[12.6px] font-bold nums',
  athleteName: 'truncate text-[14px] whitespace-nowrap',
  position: 'text-[9px] font-semibold tracking-[-.01em] whitespace-nowrap text-tx4 uppercase',
  team: 'flex min-w-0 items-center gap-[9px] compact:hidden',
  teamName: 'truncate text-[11.7px] font-bold tracking-[-.01em] whitespace-nowrap text-tx2',
  goals: 'text-center text-[17px] font-extrabold text-ac nums',
  games: 'text-center text-[14px] font-semibold text-tx2 nums',
  emptyState: 'px-4 py-6 text-center text-[12.5px] text-tx4',
  footnote: 'mt-3 text-[12px] text-tx4',
} as const
