export const usersTableStyles = {
  table: 'flex flex-col overflow-hidden rounded-card border border-bd bg-pan',
  headerRow: 'flex items-center gap-3 border-b border-bd2 px-3 pt-[9px] pb-2 text-[10px] tracking-[.05em] text-tx4 mobile:hidden',
  nameHeader: 'min-w-0 flex-1',
  statusHeader: 'w-[70px] flex-none',
  lastSignInHeader: 'w-[118px] flex-none',
  actionsHeader: 'w-[260px] flex-none text-right',
  row: 'flex items-center gap-3 px-3 py-[10px] mobile:flex-wrap',
  rowOdd: 'bg-pan0',
  rowEven: 'bg-pan',
  nameCell: 'flex min-w-0 flex-1 items-baseline gap-2',
  username: 'truncate text-[13.5px] font-bold tracking-[-.01em] text-tx',
  currentUserTag: 'flex-none text-[9.5px] tracking-[.06em] text-tx5',
  statusCell: 'w-[70px] flex-none text-[10.5px] font-bold tracking-[.04em]',
  statusActive: 'text-ac2',
  statusInactive: 'text-tx5',
  lastSignInCell: 'w-[118px] flex-none text-[11px] tracking-[.04em] text-tx3 nums',
  actionsCell: 'flex w-[260px] flex-none items-start justify-end gap-2 mobile:w-full mobile:justify-start',
} as const
